### ISSUE TITLE
Best fit matching for commodity names

### ISSUE THREAD

**Issue by Lknechtli** [stringandstickytape/RegulatedNoise#15]
A best fit match to commodity names when OCRing the markets would make it much more accurate - for instance, I've seen numbers show up in commodity names.  Restricting it to letters for the names, and numbers for prices etc would reduce the number of errors.

**Comment by stringandstickytape** [comment]
It does do Levenshtein similarity tests between commodity names.  Maybe that list needs expanding or the algorithm needs to be more tolerant of differences on longer names.  Do you have any specific examples?

**Comment by Lknechtli** [comment]
![typo2](https://cloud.githubusercontent.com/assets/4392704/5697095/c7c5ad04-99b4-11e4-9d2b-7f22ae520afd.png)
![typo3](https://cloud.githubusercontent.com/assets/4392704/5697094/c7c1ebd8-99b4-11e4-8349-e8566c80e451.png)
![typo4](https://cloud.githubusercontent.com/assets/4392704/5697096/c7c5c5a0-99b4-11e4-8f3b-9ec6a8a99ec9.png)
![typo5](https://cloud.githubusercontent.com/assets/4392704/5697097/c7c69a2a-99b4-11e4-9c7e-db2dba9d032c.png)
![typo6](https://cloud.githubusercontent.com/assets/4392704/5697098/c7c70b2c-99b4-11e4-9d25-b296b6dd8a11.png)
![typo1](https://cloud.githubusercontent.com/assets/4392704/5697099/c7c87408-99b4-11e4-9263-594929629008.png)

**Comment by stringandstickytape** [comment]
Weird.  These are all in the hard-coded list of commodity names, and I've just run them through MRmP's tweaked levenshtein algorithm - they all got autocorrected properly.

You can either:
a) try deleting your autosave.csv and retrying the screenshots - i wonder if it is related to existing commodity names in your autosave.csv, or
b) post a link to a zip file containing your autosave.csv, calibration.txt and (say) the HYDROGEN FUEL Curie Gateway screenshot, so I can try on this side.  

It seems to be working fine for me - but I regularly delete my autosave.csv so that could be relevant :/

**Comment by Lknechtli** [comment]
uploaded them to onedrive:
http://1drv.ms/1FILRi9

**Comment by stringandstickytape** [comment]
Awesome.  This has pointed me to a HUGE HOLE in the Levenshtein algorithm, namely: it doesn't work.  I have swapped in one that does and the problem is fixed.  V1.73 includes the fix.

Note that for two of the commodity names, "FRUIT AND VEGETABLES" and one other, it will still ask you to correct it.  This is because you have (something like) "FRUTT AND VEGETABLES" and it can't decide if the correct answer is that or "FRUIT AND VEGETABLES" because they both look like good candidates.

The fix is to remove the bad commodity names from your AutoSave.csv - then this problem will go away.  A commodity rename feature, like the station rename feature, is issue #17...

**Comment by Lknechtli** [comment]
Awesome. Seems to be working much better now.
