### ISSUE TITLE
Scrollbar for current screenshot being OCR'ed

### ISSUE THREAD

**Issue by Lknechtli** [stringandstickytape/RegulatedNoise#35]
Right now pretty much all you can see is the station name.  Either add a scrollbar, or resize the image to fit.

**Comment by stringandstickytape** [comment]
Weird, I thought this was already in.  Maybe I'm thinking of something else.  I guess scrollbars are more useful than resize-to-fit because I doubt you can read the text if we resize-to-fit, and I can't think of any other purpose to it apart from seeing that it's actually doing something.

**Comment by Lknechtli** [comment]
Whups, nevermind it's already in. My bad, was looking at the wrong version.

**Comment by stringandstickytape** [comment]
LOL, couldn't remember for the life of me! And won't (on a point of principle) run the app or download the code while I'm at work, because then (technically) it might become their property!! :)

Thx for reporting, investigating, feeding back and closing.  The GitHub issue log is becoming entirely pivotal as to managing the app; poring over the forum thread isn't manageable now we're up to about 100+ downloads a day.
