### ISSUE TITLE
v1.83 Current System not refreshing

### ISSUE THREAD

**Issue by mblob** [stringandstickytape/RegulatedNoise#49]
In v 1.83 Current System is not refreshing. It shows the correct system when launching the program, then it says there.

Revert to 1.82 solved the problem.

**Comment by stringandstickytape** [comment]
This should happen within a ten-second window of arriving in the system.
Th eonly difference between 1.82 and 1.83 is that the log read is carried
out once every ten seconds, rather than as fast as the system can possibly
handle (hence flatlining one CPU core).

Could you retry with v1.83 and see if the system name does update within
ten seconds please?  I don't have time to try this at the moment...

**Comment by Klaus-at** [comment]
It does not work with 1.8.3. I see in procmon that the correct log file is opened regularly, but the GUI does not actually update the current system. This also has effects on the OCR process, as it assigns the stations to the incorrect system.

**Comment by stringandstickytape** [comment]
Thx for the details.  Fixed in v1.83 :-)
